USE `library`;

INSERT INTO `authors` (`name`)
VALUES ('Alexander Belyaev'),
       ('Alexander Volkov'),
       ('Alexander Griboyedov'),
       ('Alexander Grin'),
       ('Alexandr Duma'),
       ('Alexander Ostrovsky'),
       ('Alexander Pushkin'),
       ('Alexey Tolstoy'),
       ('Anton Chekhov'),
       ('Arkady and Boris Strugatsky'),
       ('Arthur Conan Doyle'),
       ('Boris Vasiliev'),
       ('Boris Pasternak'),
       ('Valentin Kataev'),
       ('Veniamin Kaverin'),
       ('Victor Hugo'),
       ('Vladimir Bogomolov'),
       ('Vladimir Obruchev'),
       ('Gabriel Garcia Marquez'),
       ('Grigory Belykh, L. Panteleev'),
       ('Daniel Defoe'),
       ('Jack London'),
       ('George Orwell'),
       ('Jules Verne'),
       ('Ivan Goncharov'),
       ('Ivan Turgenev'),
       ('Ilya Ilf, Evgeny Petrov'),
       ('Johann Wolfgang von Goethe'),
       ('Konstantin Simonov'),
       ('Lev Tolstoy'),
       ('Leonid Filatov'),
       ('Mark Twain'),
       ('Michael Bulgakov'),
       ('Mikhail Lermontov'),
       ('Mikhail Sholokhov'),
       ('Nikolay Gogol'),
       ('Stanislav Lem'),
       ('Fedor Dostoevsky'),
       ('Charlotte Bronte'),
       ('Erich Maria Remarque'),
       ('Ernest Hemingway'),
       ('Yulian Semyonov'),
       ('Leo Tolstoy'),
       ('Fyodor Dostoevsky'),
       ('Anton Chekhov'),
       ('William Shakespeare');

INSERT INTO `books` (`author_id`, `title`)
VALUES (1, 'Amphibian Man'),
       (2, 'Wizard of Oz'),
       (3, 'Woe from Wit'),
       (4, 'Scarlet Sails'),
       (5, 'Vicomte de Bragelonne, or Ten years later'),
       (5, 'The Count of Monte Cristo'),
       (5, 'Countess de Monsoro'),
       (5, 'Twenty years later'),
       (5, 'Forty five'),
       (5, 'Three Musketeers'),
       (6, 'Dowry'),
       (7, 'Boris Godunov'),
       (7, 'Dubrovsky'),
       (7, 'Eugene Onegin'),
       (7, 'The Captains Daughter'),
       (7, 'The Bronze Horseman'),
       (7, 'Queen of Spades'),
       (7, 'Belkins Tales'),
       (7, 'Ruslan and Lyudmila'),
       (8, 'Peter the Great'),
       (8, 'Going through the throes'),
       (9, 'The Cherry Orchard'),
       (9, 'Hunting Drama'),
       (9, 'Uncle Vanya'),
       (9, 'Ward No. 6'),
       (9, 'Stories'),
       (9, 'Three Sisters'),
       (9, 'Seagull'),
       (10, 'Roadside Picnic'),
       (10, 'Its hard to be a god'),
       (11, 'The Return of Sherlock Holmes'),
       (11, 'The Adventures of Sherlock Holmes'),
       (11, 'The Hound of the Baskervilles'),
       (12, 'The Dawns Here Are Quiet'),
       (13, 'Doctor Zhivago'),
       (14, 'The lone sail turns white'),
       (15, 'Two captains'),
       (16, 'Les Miserables'),
       (16, 'Notre Dame Cathedral'),
       (17, 'Moment of Truth (In August 44)'),
       (18, 'Sannikov Land'),
       (19, 'One Hundred Years of Solitude'),
       (20, 'Republic of SHKID'),
       (21, 'Robinson Crusoe'),
       (22, 'White Fang'),
       (23, '1984'),
       (24, 'Twenty thousand leagues under the sea'),
       (24, 'Children of Captain Grant'),
       (24, 'Mysterious Island'),
       (25, 'Oblomov'),
       (26, 'Nest of Nobles'),
       (26, 'Hunters Notes'),
       (26, 'Fathers and Sons'),
       (26, 'Rudin'),
       (27, 'Twelve chairs'),
       (27, 'Golden Calf'),
       (28, 'Faust'),
       (29, 'The Living and the Dead'),
       (30, 'Anna Karenina'),
       (30, 'War and Peace'),
       (30, 'Resurrection'),
       (30, 'Childhood. Adolescence. Youth'),
       (30, 'Prisoner of the Caucasus'),
       (30, 'Hadji Murad'),
       (31, 'About Fedot the archer, a dashing fellow'),
       (32, 'The Adventures of Huckleberry Finn'),
       (32, 'The Adventures of Tom Sawyer'),
       (33, 'Running'),
       (33, 'White Guard'),
       (33, 'Notes of a young doctor'),
       (33, 'Ivan Vasilyevich'),
       (33, 'The Master and Margarita'),
       (33, 'Morphine'),
       (33, 'Heart of a Dog'),
       (34, 'Hero of Our Time'),
       (35, 'The fate of man'),
       (35, 'Quiet Don'),
       (36, 'Evenings on a farm near Dikanka'),
       (36, 'Dead Souls'),
       (36, 'Petersburg Tales'),
       (36, 'The Examiner'),
       (36, 'Taras Bulba'),
       (36, 'Overcoat'),
       (37, 'Solaris'),
       (38, 'Poor people'),
       (38, 'Demons'),
       (38, 'The Brothers Karamazov'),
       (38, 'Notes from the House of the Dead'),
       (38, 'Player'),
       (38, 'Idiot'),
       (38, 'Teenager'),
       (38, 'Crime and Punishment'),
       (38, 'The village of Stepanchikovo and its inhabitants'),
       (38, 'Humiliated and Insulted'),
       (39, 'Jane Eyre'),
       (40, 'Three comrades'),
       (40, 'Arc de Triomphe'),
       (40, 'Black Obelisk'),
       (41, 'The Old Man and the Sea'),
       (42, 'Seventeen Moments of Spring');